outspecies:
  - OCS
  - CO
  - CS
  - CH3OH
param_dict:
  endAtFinalDensity: False
  freefall: False
  writeStep: 1
  initialDens: 10_000
  initialTemp: 10.0
  finalDens: 100_000
  finalTime: 5_000_000
  outputFile: examples/test/staticFull.dat
  abundSaveFile: examples/test/startStatic.dat
model:
  cloud
settings:
  hdf_save: examples/test/test-store.h5
  get_rates: true
  run_model: true